#!/bin/sh
# shell script to prepend i3status with more stuff

i3status --config ~/.i3/i3status | while :
do
        read line
        weather="$(cat /home/test/.i3/weather)"
        echo "$line|$weather" || exit 1
done

